### PR TITLE
Support circular dependencies with loops of length > 1

### PR DESCRIPTION
**Pull request by NexZhu**
# Why

This PR add support for any circular dependencies with loops of length > 1 (unless there are missing dependencies)

Before this PR, This repo already supported types depending on itself with `z.lazy()` like:
```ts
interface Person {
  friend: Person
}
```

With `z.lazy()` actually circular dependencies with loops of length > 1 can also be supported, for example:
```ts
      export interface EvilPlan {
        description: string;
        details: EvilPlanDetails;
      }

      export interface EvilPlanDetails {
        parent: EvilPlan;
        steps: string[];
      }
```

With this PR will generate:
```ts
        export const evilPlanSchema: z.ZodSchema<EvilPlan> = z.lazy(() => z.object({
            description: z.string(),
            details: evilPlanDetailsSchema
        }));

        export const evilPlanDetailsSchema: z.ZodSchema<EvilPlanDetails> = z.lazy(() => z.object({
            parent: evilPlanSchema,
            steps: z.array(z.string())
        }));
```

### CODE REVIEW

**Comment by NexZhu** [comment]
This PR addionally improve the generation process:

1. Every progressive iteration will at least find a direct or indirect missing dependency (1st iteration will find all direct missing dependencies, 2nd iteration will find all indirect missing dependencies depending on any direct missing dependencies, etc.), or at least one new type that can be generated (all its dependencies become able to be generated by this time).
2. If an iteration did not find any direct or indirect missing dependencies nor any new types that can be generated, the whole process can immediately end since no further iterations can possibly find them again.
3. To sum up, we can use a `done` flag to track if each iteration is still making progress and end the process as soon as there's no more progress being made, this way there won't be wasted iterations and dead loops won't happen.
4. Max iteration number flag is removed since it's not needed any more.

**Comment by NexZhu** [comment]
@fabien0102 Please check this out soon when you have time, so I can open further improvement PRs after this get merged, thanks! 😄

**Review by fabien0102 — APPROVED** [review]
Just amazing! Huge thanks for this amazing contribution!!! 😍

**Comment by NexZhu** [comment]
@fabien0102 Thank you too for this amazing tool!

**Pull request merged**
