### PR TITLE
Handling imports of generated types

### PR DESCRIPTION
**Pull request by tvillaren**
# Why

Following #135 (once it's merged), this PR adds support for automatic resolution of ts-to-zod-generated schemas, based on the config file provided: if the current input file imports a type from a file referenced in the `ts-to-zod.config.js` file, then the generated file will automatically resolve the reference to the corresponding schema. 

```ts

//ts-to-zod.config.js
/**
 * ts-to-zod configuration.
 *
 * @type {import("./src/config").TsToZodConfig}
 */
module.exports = [
  {
    name: "villain",
    input: "src/villain.ts",
    output: "src/generated/villain.zod.ts",
    getSchemaName: (id) => `z${id}`
  },
   {
    name: "hero",
    input: "src/example/heros.ts",
    output: "src/example/heros.zod.ts",
  },
];

// heros.ts (input)
import { Villain } from "../villain";

export interface Hero {
  name: string;
  nemesis: Villain;
}

// heros.zod.ts (output)
import { zVillain } from "../generated/villain.zod";

export const heroSchema = z.object({
  name: z.string(),
  nemesis: zVillain;
});
``` 

This opens up the possibility of handling multiple files in one generation (by adding them to the config file first for instance).

### CODE REVIEW

**Comment by tvillaren** [comment]
Hello @dan-blank, @fabien0102 👋, 

Following the discussion in #135, I fiddled a bit and decided to go for this solution of Zod Schemas. 
Happy to discuss this.

**Comment by anthony-dandrea** [comment]
This worked pretty well for me when testing in my project. One issue I ran into is that I use [proto-loader-gen-types](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/README.md) for generating some of my types from protos. I found that it doesn't work with there are parenthesis around the types which is how proto-loader-gen-types generates types. Example:

```js
// DoesntWork.ts
import type { BoolValue } from "google/protobuf/BoolValue";
export interface Broken {
  bool: (BoolValue | null);
}

// DoesWork.ts
import type { BoolValue } from "google/protobuf/BoolValue";
export interface Works {
  bool: BoolValue | null;
}

// google/protobuf/BoolValue.ts
export interface BoolValue {
  'value': (boolean);
}
```

**Comment by tvillaren** [comment]
Hey @anthony-dandrea, 

The issue you mentioned was not directly related to this PR, but it's an easy fix. 
The fix is there: https://github.com/fabien0102/ts-to-zod/pull/152

You can cherry pick the commit in your branch while waiting for an approval. I'll rebase the import-related branches when it's  the fix is merged.

**Comment by schiller-manuel** [comment]
Can you please explain the difference between this PR and https://github.com/fabien0102/ts-to-zod/pull/164 ?
Would love to get all those PRs merged.

**Comment by tvillaren** [comment]
Hey @schiller-manuel,

As far as I see, it seems that they are multiple PRs to handle import: 

Those 3 are not from me, and they felt like too much changes in one pass to me. 
- https://github.com/fabien0102/ts-to-zod/pull/118
- https://github.com/fabien0102/ts-to-zod/pull/126
- https://github.com/fabien0102/ts-to-zod/pull/164 based on https://github.com/fabien0102/ts-to-zod/pull/118

I took a different approach with https://github.com/fabien0102/ts-to-zod/pull/135 + https://github.com/fabien0102/ts-to-zod/pull/148 (the current one):

👉 https://github.com/fabien0102/ts-to-zod/pull/135 aimed at handling `import` statement *in one file* only. It does work, as I've been using this for months now on my company project. 
However, due to validation errors that I haven't been able to fix (see https://github.com/fabien0102/ts-to-zod/issues/186), it would be kind of a breaking change in the current state, as non-zod imported types would only pass validation in most cases (the generated zod validators usually work in that case).

👉 the current PR https://github.com/fabien0102/ts-to-zod/pull/148 adds a very simple way of handling multiple file generation, by relying on the `ts-to-zod.config.js` configuration file to describe all the files in the "ZOD filesystem". I did that as a first step, to rely on existing bricks and not do a big bang refactoring like other approaches above. 
Again, this work in my project. I haven't rebased to the latest `ts-to-zod` though because of the validation errors in https://github.com/fabien0102/ts-to-zod/pull/135 

👉 in my mind, a third PR would have finished the work to automate filesystem browsing and generate all zod files in the right order based on `import` statements and all. Haven't looked at it yet (but the need in my company project is going to arise to if we can move on with the rest, it would be great 😉)

## How to move on

I see several alternatives to move on with my 2 PRs: 
1. Find a solution to external imports validation issues, as discussed on https://github.com/fabien0102/ts-to-zod/issues/186, implement in https://github.com/fabien0102/ts-to-zod/pull/135, and then integrate to https://github.com/fabien0102/ts-to-zod/pull/148
2. Drop the "external import" bit and focus only on "internal imports" of files which are also converted to zod schemas. This would mean a bit of rework, it would add support for multiple generated files (through `ts-to-zod.config.js` for now), but limited to referencing other "internal" types.  
3. Acknowledge that we don't fully support external imports and merge both PRs (after rebasing).

Any thoughts welcome are welcome!

**Comment by tvillaren** [comment]
Hello @schiller-manuel, @fabien0102, 

I rebased this PR and it's (finally) ready for merging. 
Now `ts-to-zod` fully supports imports of types that are also converted into zod schema on the condition that all files are listed in the configuration file. 

Next step would be to build the list "on the fly" (from a folder passed as argument for instance).

**Review by schiller-manuel — COMMENTED** [review]
LGTM!
> "Next step would be to build the list "on the fly" (from a folder passed as argument for instance).
Should we wait to release a new version until this has been implemented?

**Comment by tvillaren** [comment]
I don't think I will have time in the next few weeks to deep dive on this but would love to at one point!
Let's merge, I know some people (including me) are using this branch in their project.

**Comment by schiller-manuel** [comment]
Thanks a lot for your work!

**Pull request merged**
