### PR TITLE
fix!: use default passed to generate

### LINKED ISSUE #213: getSchemaName not applied to imports
## Bug description

When using the `generate` api providing a custom `getSchemaName` the named imports for other schemas don't use the custom `getSchamaName`

```ts
const schema = generate({
  sourceText,
  inputOutputMappings: mappings,
  getSchemaName(identifier) {
    // Return the type name as is with Schema suffix eg. TypeNameSchema
    return identifier + "Schema";
  },
});
```

### Input

```ts
import type { AliasTypeSummary } from "./AliasTypeSummary.ts";
import type { Entity } from "./Entity.ts";
export type Alias = {
  Id?: number;
  AliasFirstName?: string;
  AliasLastName?: string;
  AliasType?: AliasTypeSummary;
  Constituent?: Entity;
  EditIndicator?: boolean;
  UpdatedDateTime?: string;
  CreatedDateTime?: string;
  CreateLocation?: string;
  CreatedBy?: string;
  UpdatedBy?: string;
};
```

### Expected output

```ts
// Generated by ts-to-zod
import { z } from "zod";

import { aliasTypeSummarySchema } from "./AliasTypeSummary.schema.ts";
import { entitySchema } from "./Entity.schema.ts";

export const AliasSchema = z.object({
  Id: z.number().optional(),
  AliasFirstName: z.string().optional(),
  AliasLastName: z.string().optional(),
  AliasType: aliasTypeSummarySchema.optional(),
  Constituent: entitySchema.optional(),
  EditIndicator: z.boolean().optional(),
  UpdatedDateTime: z.string().optional(),
  CreatedDateTime: z.string().optional(),
  CreateLocation: z.string().optional(),
  CreatedBy: z.string().optional(),
  UpdatedBy: z.string().optional(),
});

```

### Actual output

```ts
// Generated by ts-to-zod
import { z } from "zod";

import { AliasTypeSummarySchema } from "./AliasTypeSummary.schema.ts";
import { EntitySchema } from "./Entity.schema.ts";

export const AliasSchema = z.object({
  Id: z.number().optional(),
  AliasFirstName: z.string().optional(),
  AliasLastName: z.string().optional(),
  AliasType: AliasTypeSummarySchema.optional(),
  Constituent: EntitySchema.optional(),
  EditIndicator: z.boolean().optional(),
  UpdatedDateTime: z.string().optional(),
  CreatedDateTime: z.string().optional(),
  CreateLocation: z.string().optional(),
  CreatedBy: z.string().optional(),
  UpdatedBy: z.string().optional(),
});
```

**Versions**

- Typescript: `v5.3.3`
- Zod: `v3.22.4`

### PR DESCRIPTION
**Pull request by deckchairlabs**
# Why

This PR resolves #213, a very simple change.

### CODE REVIEW

**Comment by tvillaren** [comment]
Hey @deckchairlabs, 

Thank you for your PR, it seems that the tests don't pass anymore. 
Would you mind having a look?

Also, you committed a few changes that seem to be only spacing changes 👉 there is a `yarn lint` task that you may want to use to clean those out.

**Comment by deckchairlabs** [comment]
Apologies! I rushed this at the end of the day! Wondering how you feel about this change, since it does change behavior, I imagine people updating might have to rename a bunch of imports now.

**Comment by schiller-manuel** [comment]
if this is a breaking change we can only merge it in v4

**Comment by tvillaren** [comment]
Thanks for the update 🙏 

Indeed, that would change the current behaviour implemented last month. 
To sum up: 

**Current**
- Generated file: `Generate getSchemaName | DEFAULT` 
- Imported files: `IO Mapping getSchemaName | DEFAULT` 

**Proposed**
- Generated file: `Generate getSchemaName | DEFAULT` 
- Imported files: `IO Mapping getSchemaName | Generate getSchemaName | DEFAULT` 

So this would mean that users relying on the `generate` method with a specific `getSchemaName` that they don't want to apply for imports would need to update their config file to set an alternative their (i.e. what users currently have to do in reverse). 
*This concerns users who updated to 3.7.3 and starting using the import handling feature.*

I don't have a strong opinion for proposed or current behaviour: I implemented the import handling feature without giving this particular point a thought, as I myself rely on the default in my work 😅

**Pull request merged**
